import Link from 'next/link';
import Navbar from './components/navbar';



import './globals.css'
import { Provider } from 'react-redux'
// import { Store } from 'redux'
import { Providers } from './provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <html>
      <head/>
      <body>
       <Providers>
        <Navbar/>

        {children}
        </Providers>


      </body>
      </html>
  )
}
